StartupEvents.registry('item', e => {
    e.create('general_circuit_ulv').texture('kubejs:item/circuit/general/general_circuit_ulv').tag('gtceu:circuits/ulv').tag('gtceu:circuits')
    e.create('general_circuit_lv').texture('kubejs:item/circuit/general/general_circuit_lv').tag('gtceu:circuits/lv').tag('gtceu:circuits')
    e.create('general_circuit_mv').texture('kubejs:item/circuit/general/general_circuit_mv').tag('gtceu:circuits/mv').tag('gtceu:circuits')
    e.create('general_circuit_hv').texture('kubejs:item/circuit/general/general_circuit_hv').tag('gtceu:circuits/hv').tag('gtceu:circuits')
    e.create('general_circuit_ev').texture('kubejs:item/circuit/general/general_circuit_ev').tag('gtceu:circuits/ev').tag('gtceu:circuits')
    e.create('general_circuit_iv').texture('kubejs:item/circuit/general/general_circuit_iv').tag('gtceu:circuits/iv').tag('gtceu:circuits')
    e.create('general_circuit_luv').texture('kubejs:item/circuit/general/general_circuit_luv').tag('gtceu:circuits/luv').tag('gtceu:circuits')
    e.create('general_circuit_zpm').texture('kubejs:item/circuit/general/general_circuit_zpm').tag('gtceu:circuits/zpm').tag('gtceu:circuits')
    e.create('general_circuit_uv').texture('kubejs:item/circuit/general/general_circuit_uv').tag('gtceu:circuits/uv').tag('gtceu:circuits')
    e.create('general_circuit_uhv').texture('kubejs:item/circuit/general/general_circuit_uhv').tag('gtceu:circuits/uhv').tag('gtceu:circuits')
    e.create('general_circuit_uev').texture('kubejs:item/circuit/general/general_circuit_uev').tag('gtceu:circuits/uev').tag('gtceu:circuits')
    e.create('general_circuit_uiv').texture('kubejs:item/circuit/general/general_circuit_uiv').tag('gtceu:circuits/uiv').tag('gtceu:circuits')
    e.create('general_circuit_uxv').texture('kubejs:item/circuit/general/general_circuit_uxv').tag('gtceu:circuits/uxv').tag('gtceu:circuits')
    e.create('general_circuit_opv').texture('kubejs:item/circuit/general/general_circuit_opv').tag('gtceu:circuits/opv').tag('gtceu:circuits')
    e.create('general_circuit_max').texture('kubejs:item/circuit/general/general_circuit_max').tag('gtceu:circuits/max').tag('gtceu:circuits')
    e.create('fear_in_a_bottle')
    e.create('fighting_spirit_in_a_bottle')
    e.create('fog_in_a_bottle')
    e.create('glaceon_in_a_bottle')
    e.create('happiness_in_a_bottle')
    e.create('sand_storm_in_a_bottle')
    e.create('sleppy_in_a_bottle')
    e.create('vaporeon_in_a_bottle')
    e.create('physics_assembler')
})

// GTCEuStartupEvents.registry('gtceu:material', e => {
//     GTMaterials.WroughtIron.addFlags(GTMaterialFlags.GENERATE_ROTOR)
//     e.create('caminite_brick').ingot().color(0xedd7af).iconSet(GTMaterialIconSet.QUARTZ).flags(GTMaterialFlags.GENERATE_PLATE)
//     e.create('infused_alloy').ingot().color(0xea463e).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.LV], 16, 0, true)
//     e.create('dragon').ingot().color(0x9600ff).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.UXV], 16, 2, false).flags(GTMaterialFlags.GENERATE_PLATE).flags(GTMaterialFlags.GENERATE_GEAR).flags(GTMaterialFlags.GENERATE_ROD)
// })