ServerEvents.recipes(e => {
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'gtceu:diamond_plate'},"cast_consumed":true,"cooling_time":75,"fluid":{"amount":144,"fluid":"gtceu:rose_gold"},"result":'embers:dawnstone_ingot'})
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'minecraft:iron_nugget'},"cast_consumed":true,"cooling_time":100,"fluid":{"amount":144,"fluid":"gtceu:iron"},"result":'gtceu:wrought_iron_ingot'})
    e.custom({"type":"tconstruct:casting_basin","cast":{"item":'minecraft:iron_ingot'},"cast_consumed":true,"cooling_time":800,"fluid":{"amount":1296,"fluid":"gtceu:iron"},"result":'gtceu:wrought_iron_block'})
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'tconstruct:obsidian_pane'},"cast_consumed":true,"cooling_time":100,"fluid":{"amount":576,"fluid":"gtceu:steel"},"result":'oritong:steel_upgrade_smithing_template'})
    e.custom({"type":"tconstruct:casting_table","cast":{"tag":'tconstruct:casts/single_use/gem'},"cast_consumed":true,"cooling_time":180,"fluid":{"amount":100,"fluid":"tconstruct:molten_glass"},"result":'gtceu:glass_tube'})
    e.custom({"type":"tconstruct:casting_table","cast":{"tag":'tconstruct:casts/multi_use/gem'},"cast_consumed":false,"cooling_time":180,"fluid":{"amount":100,"fluid":"tconstruct:molten_glass"},"result":'gtceu:glass_tube'})
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'tgears:whisk_cast_with_part'},"cast_consumed":true,"cooling_time":250,"fluid":{"amount":1296,"fluid":"gtceu:iron"},"result":'tgears:whisk_cast_with_whisk'})
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'tgears:hand_cast_with_part'},"cast_consumed":true,"cooling_time":250,"fluid":{"amount":1296,"fluid":"gtceu:brass"},"result":'tgears:hand_cast_with_brass_hand'})
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'create:brass_hand'},"cast_consumed":false,"cooling_time":100,"fluid":{"amount":144,"fluid":"gtceu:gold"},"result":'tgears:hand_cast_with_brass_hand'})
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'create:whisk'},"cast_consumed":false,"cooling_time":100,"fluid":{"amount":144,"fluid":"gtceu:gold"},"result":'tgears:whisk_cast_with_whisk'})
    e.custom({"type":"tconstruct:casting_basin","cooling_time":120,"fluid":{"amount":2250,"fluid":"tconstruct:molten_ender"},"result":'gtceu:ender_pearl_block'})
    e.custom({"type":"tconstruct:casting_basin","cast":{"item":'create:andesite_alloy'},"cast_consumed":true,"cooling_time":200,"fluid":{"amount":500,"fluid":"tconstruct:molten_clay"},"result":'gtceu:coke_oven_bricks'})
    e.custom({"type":"tconstruct:casting_table","cast":{"item":'gtceu:andesite_alloy_dust'},"cast_consumed":true,"cooling_time":20,"fluid":{"amount":50,"fluid":"oritong:latex"},"result":'create:andesite_alloy'})
    e.custom({"type":"tconstruct:casting_basin","cast":{"item":'minecraft:barrel'},"cast_consumed":true,"cooling_time":150,"fluid":{"amount":200,"fluid":"oritong:latex"},"result":'gtceu:wood_drum'})
    e.custom({"type":"tconstruct:casting_basin","cast":{"item":'kubejs:wood_block'},"cast_consumed":true,"cooling_time":100,"fluid":{"amount":125,"fluid":"gtceu:creosote"},"result":'gtceu:treated_wood_planks'})
})
