ServerEvents.recipes(e => {
    //————1级净化水————
    e.recipes.gtceu.chemical_reactor().itemInputs('2x gtceu:aluminum_hydroxide_dust').inputFluids(Fluid.of('gtceu:sulfuric_acid', 3000)).itemOutputs('gtceu:aluminum_sulfate_dust').outputFluids(Fluid.of('water', 6000)).EUt(GTValues.VA[GTValues.MV]*0.7).duration(7.8*20)
    e.recipes.gtceu.vacuum_freezer().itemInputs('gtceu:aluminum_sulfate_dust').inputFluids(Fluid.of('gtceu:molten_potassium_pyrosulfate', 144), Fluid.of('water', 25000)).itemOutputs('2x gtceu:alum_gem').outputFluids(Fluid.of('gtceu:sulfuric_acid', 1000)).EUt(GTValues.VA[GTValues.HV]*0.36).duration(2.9*20).cleanroom(CleanroomType.CLEANROOM)
    e.recipes.gtceu.flocculation_purification_unit().itemInputs('3x gtceu:alum_dust').inputFluids(Fluid.of('water', 11500)).outputFluids(Fluid.of('gtceu:grade_1_purified_water', 9999)).itemOutputs('3x gtceu:small_aluminum_hydroxide_dust').chancedOutput('embers:ember_shard', 300, 0).chancedOutput('ars_nouveau:starbuncle_shards', 150, 0).duration(600 * 20).EUt(GTValues.VA[GTValues.MV]).cleanroom(CleanroomType.CLEANROOM)
    //————2级净化水————
    e.recipes.gtceu.assembler().itemInputs('32x gtceu:activated_carbon_dust', '16x gtceu:small_sieved_zeolite_powder_dust', '8x gtceu:zinc_foil').itemOutputs('kubejs:composite_purification_filter').duration(10 * 20).EUt(GTValues.VA[GTValues.IV] * 0.43).cleanroom(CleanroomType.CLEANROOM)
    e.recipes.gtceu.clarifier_purification_unit().chancedInput('kubejs:composite_purification_filter', 1250, 0).circuit(1).inputFluids(Fluid.of('gtceu:grade_1_purified_water', 875)).chancedOutput('gtceu:clay_dust', 600, 0).chancedOutput('gtceu:silicon_dioxide_dust', 300, 0).chancedOutput('mekanism:salt', 150, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 560), 3500, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 510), 3000, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 460), 2500, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 410), 2000, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 360), 1500, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 300), 1000, 0).cleanroom(CleanroomType.CLEANROOM).EUt(GTValues.VA[GTValues.EV]).duration(120 * 20)
    e.recipes.gtceu.clarifier_purification_unit().chancedInput('kubejs:composite_purification_filter', 750, 0).circuit(2).inputFluids(Fluid.of('gtceu:grade_1_purified_water', 875), Fluid.of('gtceu:grade_2_purified_water', 90)).chancedOutput('gtceu:clay_dust', 600, 0).chancedOutput('gtceu:silicon_dioxide_dust', 300, 0).chancedOutput('mekanism:salt', 150, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 460), 4500, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 427), 4000, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 394), 3500, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 361), 3000, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 328), 2500, 0).chancedFluidOutput(Fluid.of('gtceu:grade_2_purified_water', 295), 2000, 0).cleanroom(CleanroomType.CLEANROOM).EUt(GTValues.VA[GTValues.EV]).duration(120 * 20)
})