let key_zh_cn = [
    ['block.minecart.stone', '§o石头'],
    ["kubejs.multiblock.dtpf.coil_parallel", "同时处理至多%s个配方"],
    ['oritong.menu.back', '再见，只为再见'],
    ['oritong.menu.single', '孤寂旅途'],
    ['oritong.menu.multi', '团队执勤'],
    ['oritong.menu.config', '热身运动'],
    ['oritong.menu.mod', '检视装备'],
    ['oritong.menu.report', '报告问题'],
    ['oritong.menu.report_push', '前往墙后的世界'],
    ['oritong.menu.time', '，你已经打开游戏'],
    ['oritong.menu.time2', '秒了，闭上眼睛休息一下吧！'],
    ['oritong.menu.auxiliary', '辅助功能设置'],
    ['oritong.menu.auxiliary_push', '但这并不是外挂'],
    ['oritong.menu.loding', '少女折寿中……'],
    ["kubejs.multiblock.digester.current_eut_multiplier", "当前能耗倍数: %s"],
    ["kubejs.multiblock.large_chemical_plant.coil_parallel", "线圈并行数: %s"],
    ["kubejs.multiblock.large_chemical_plant.current_duration_multiplier", "当前耗时倍数: %s"],
    ["kubejs.multiblock.large_chemical_plant.current_eut_multiplier", "当前耗能倍数: %s"],
    ['kubejs.multiblock.petrochemical_factory.current_speed', '当前运行速度：%s'],
    ["kubejs.multiblock.blaze_blast_furnace.heat_capacity", "热容：%sK"],
    ["kubejs.multiblock.blaze_blast_smelter.heat_capacity", "热容：%sK"],
    ["kubejs.multiblock.platdur_s_gate.current_speed", "当前运行速度：%s"],
    ["tagprefix.starforge_hexlux", "%s星铸六耀晶石"],
    ["tagprefix.raw_ceramic_block", "%s陶瓷粗坯"],
    ['item.functionalstorage.max_storage_upgrade', '最大存储量升级']
]
let item_js_key_zh_cn = [
    ['stone_hammer', '石锤'],
    ['raw_apothecary', '花药台粗坯'],
    ['the_source_of_the_earth', '泥土之源'],
    ['orundum', '合成玉'],
    ['originium_shard', '源石碎片'],
    ['originium', '至纯源石'],
    ['raw_compressed_fireclay', '定型耐火黏土'],
    ['raw_vacuum_tube', '待抽空气的二极管'],
    ['general_circuit_ulv', 'ULV通用电路'],
    ['general_circuit_lv', 'LV通用电路'],
    ['general_circuit_mv', 'MV通用电路'],
    ['general_circuit_hv', 'HV通用电路'],
    ['general_circuit_ev', 'EV通用电路'],
    ['general_circuit_iv', 'IV通用电路'],
    ['general_circuit_luv', 'LuV通用电路'],
    ['general_circuit_zpm', 'ZPM通用电路'],
    ['general_circuit_uv', 'UV通用电路'],
    ['general_circuit_uhv', 'UHV通用电路'],
    ['general_circuit_uev', 'UEV通用电路'],
    ['general_circuit_uiv', 'UIV通用电路'],
    ['general_circuit_uxv', 'UXV通用电路'],
    ['general_circuit_opv', 'OpV通用电路'],
    ['general_circuit_max', 'MAX通用电路'],
    ['watered_raw_vacuum_tube', '充满水的真空管'],
    ['vaporeon_in_a_bottle', '瓶装雨天'],
    ['sleppy_in_a_bottle', '瓶装困倦'],
    ['sand_storm_in_a_bottle', '瓶装沙暴'],
    ['happiness_in_a_bottle', '瓶装开心'],
    ['glaceon_in_a_bottle', '瓶装冰雪'],
    ['fog_in_a_bottle', '瓶装迷雾'],
    ['fighting_spirit_in_a_bottle', '瓶装斗志'],
    ['fear_in_a_bottle', '瓶装恐惧'],
    ['wood_ingot', '木锭'],
    ['silver_catalyst', '银基催化剂'],
    ['overworld_data', '主世界数据'],
    ['nether_data', '下界数据'],
    ['end_data', '末地数据'],
    ['lost_item', '§c遗忘之物'],
    ['sn1ckers', '土力架'],
    ['composite_purification_filter', '复合净化滤芯'],
    ['wood_upgrade', '木升级'],
    ['bronze_upgrade', '青铜升级'],
    ['steel_upgrade', '钢升级'],
    ['aluminium_upgrade', '铝升级'],
    ['stainless_upgrade', '不锈钢升级'],
    ['titanium_upgrade', '钛升级'],
    ['tungsten_steel_upgrade', '钨钢升级']
]
let item_ori_key_zh_cn = [
    ['steel_upgrade_smithing_template', '钢升级锻造模板'],
    ['diamond_upgrade_smithing_template', '钻石升级锻造模板'],
    ['super_glue_package', '强力胶包装']
]
let block_js_key_zh_cn = [
    ['machine_core_1', '原始机器核心'],
    ['machine_core_2', '基础机器核心'],
    ['machine_core_3', '高级机器核心'],
    ['machine_core_4', '精英机器核心'],
    ['machine_core_5', '超级机器核心'],
    ['machine_core_6', '终极机器核心'],
    ['machine_core_7', '觉醒机器核心'],
    ['wood_block', '木块'],
    ['multi_functional_casing', '多功能机器外壳'],
    ['grizzly_chute', '格筛溜槽'],
    ['compress_diamond_block', '压缩钻石块'],
    ['dimension_injection_casing', '维度注入方块'],
    ['dimension_connection_casing', '维度连接机械方块'],
    ['dimensional_stability_casing', '维度稳定方块'],
    ['dimensional_bridge_casing', '维度桥接方块'],
    ['containment_field_generator', '遏制场发生器'],
    ['blaze_casing', '炽炎机械方块'],
    ['cold_ice_casing', '凛冰机械方块']
]
let material_gt_key_zh_cn = [
    ['caminite_brick', '方镁矾'],
    ['infused_alloy', '灌注合金'],
    ['manasteel', '魔力钢'],
    ['enriched_redstone', '富集红石'],
    ['diamond_ore_leachate', '钻石矿石浸出液'],
    ['enriched_diamond', '富集钻石'],
    ['dragon', '龙晶'],
    ['sodium_aluminate', '铝酸钠'],
    ['aluminum_hydroxide', '氢氧化铝'],
    ['alumina', '氧化铝'],
    ['alumina_ceramic', '氧化铝陶瓷'],
    ['titanium_nitride_ceramic', '氮化钛陶瓷'],
    ['tungsten_tetraboride_ceramic', '四硼化钨陶瓷'],
    ['tungsten_tetraboride_mixture', '四硼化钨混合物'],
    ['sodium_hydroxide_solution', '氢氧化钠溶液'],
    ['absolute_ethanol', '绝对乙醇'],
    ['wet_sieved_zeolite_powder', '湿过筛沸石颗粒'],
    ['sieved_zeolite_powder', '过筛沸石颗粒'],
    ['silica_alumina_gel_powder', '硅铝凝胶'],
    ['silica_gel_powder', '硅胶'],
    ['silica_gel_matrix', '硅胶基质'],
    ['chloroacetic_acid', '氯乙酸'],
    ['ethyl_chloroacetate', '氯乙酸乙酯'],
    ['polyethyl_acetate_mixture', '聚乙酸乙酯混合液'],
    ['diethyl_malonate', '丙二酸二乙酯'],
    ['cobalt_chloride', '氯化钴'],
    ['cobalt_acetate', '醋酸钴'],
    ['ethyl_cyanoacetate', '氰乙酸乙酯'],
    ['pyridine', '吡啶'],
    ['ethyl_cyanoacrylate', 'α-氰基丙烯酸乙酯'],
    ['cobalt_nitrate_solution', '硝酸钴溶液'],
    ['cobalt_carbonate', '碳酸钴'],
    ['light_oil_fraction', '轻油馏分'],
    ['ammonia_solution', '氨水'],
    ['crude_light_pyridine', '粗轻吡啶'],
    ['benzene_crude_pyridine', '含苯粗轻吡啶'],
    ['azeotropic_crude_pyridine', '共沸粗轻吡啶'],
    ['refined_crude_pyridine', '精制粗轻吡啶'],
    ['acetonitrile', '乙腈'],
    ['palladium_nitrate', '硝酸钯'],
    ['palladium_activated_carbon', '吸附钯离子的活性炭'],
    ['monoethyl_malonamide', '丙二酸单乙酯酰胺'],
    ['hexamethylenetetramine', '六亚甲基四胺'],
    ['benzyl_hexamethylenetetramine_chloride', '氯化苄基六亚甲基四胺'],
    ['hexabenzylhexaazaisowurtzitane', '六苄基六氮杂异伍兹烷'],
    ['tetraacetyldibenzylhexaazaisowurtzitane', '四乙酰基二苄基六氮杂异伍兹烷'],
    ['tetraacetylhexaazaisowurtzitane', '四乙酰基六氮杂异伍兹烷'],
    ['hexanitrohexaazaisowurtzitane', '六硝基六氮杂异伍兹烷'],
    ['mixed_quartz_fiber', '混合石英纤维'],
    ['tungsten_trioxide', '三氧化钨'],
    ['benzyl_chloride', '氯苄'],
    ['benzylamine_hydrochloride', '苄胺盐酸盐'],
    ['benzylamine', '苄胺'],
    ['dried_benzylamine', '干燥苄胺'],
    ['refined_benzylamine', '精制苄胺'],
    ['bromobenzene', '溴苯'],
    ['hydrobromic_acid', '氢溴酸'],
    ['ethylene_oxide', '环氧乙烷'],
    ['wet_ethylene_oxide', '湿环氧乙烷'],
    ['silver_nitrate', '硝酸银'],
    ['fuming_sulfuric_acid', '发烟硫酸'],
    ['fuming_nitric_acid', '发烟硝酸'],
    ['fuming_nitric_acid_mixture', '发烟硝酸混酸'],
    ['ethylene_glycol', '乙二醇'],
    ['gaseous_ethylene_glycol', '气态乙二醇'],
    ['glyoxal', '乙二醛'],
    ['pink_glimmer', '粉红"微光"'],
    ['meteor_slurry', '陨石浆液'],
    ['excited_meteor_slurry', '激发态陨石浆液'],
    ['excited_space_fluid', '激发太空流体'],
    ['space_glimmer_mixture', '太空"微光"混合液'],
    ['deactivated_meteor_precipitate', '失活陨石沉淀物'],
    ['thorite', '方钍石'],
    ['hafnium_zirconium_oxide_mixture', '氧化铪-氧化锆混合物'],
    ['hafnium_oxide', '氧化铪'],
    ['zirconium_oxide', '氧化锆'],
    ['cerium_dioxide', '二氧化铈'],
    ['cerium_oxalate', '草酸铈'],
    ['cerium_oxide_iii', '氧化铈(III)'],
    ['europium_oxide_iii', '氧化铕(III)'],
    ['europium_oxide', '氧化铕'],
    ['zirconium_tetrachloride', '四氯化锆'],
    ['hafnium_tetrachloride', '四氯化铪'],
    ['low_purity_hafnium', '低纯铪'],
    ['hafnium_iodide', '碘化铪'],
    ['hafnium_waste', '铪废料'],
    ['monazite_rare_earth_residue', '独居石稀土滤渣'],
    ['neutralized_monazite_rare_earth_residue', '中和独居石稀土滤渣'],
    ['concentrated_monazite_hydroxide', '浓缩独居石氢氧化物'],
    ['cooled_concentrated_nitric_monazite_leach', '冷却浓缩硝酸独居石浸出'],
    ['red_zircon', '红锆石'],
    ['monazite_sulfate', '硫酸独居石'],
    ['acidic_monazite', '酸性独居石'],
    ['thorium_phosphate_filter_cake', '磷酸钍滤饼'],
    ['thorium_phosphate_concentrate', '磷酸钍精'],
    ['uranium_residue', '铀滤渣'],
    ['neutralized_uranium_residue', '中和铀滤渣'],
    ['dried_concentrated_monazite_rare_earth', '干燥浓缩独居石稀土'],
    ['cerium_chloride', '氯化铈'],
    ['oxalic_acid', '草酸'],
    ['monazite_rare_earth_precipitate', '独居石罕土沉淀'],
    ['heterogeneous_monazite_rare_earth_halide_mixture', '异质卤化独居石稀土混合物'],
    ['saturated_monazite_rare_earth', '饱和独居石稀土'],
    ['samarium_precipitate', '钐沉淀'],
    ['fluorosilicic_acid', '氟硅酸'],
    ['sodium_fluorosilicate', '氟硅酸钠'],
    ['fluorocarbon_lanthanum_cerium_rare_earth_turbid_slurry', '氟碳镧铈稀土浊浑液'],
    ['steam_cracked_fluorocarbon_lanthanum_cerium_slurry', '蒸汽裂化氟碳镧铈泥浆'],
    ['prepared_fluorocarbon_lanthanum_cerium_slurry', '调制氟碳镧铈泥浆'],
    ['gangue_dust', '脉石'],
    ['diluted_fluorocarbon_lanthanum_cerium_slurry', '稀释氟碳镧铈泥浆'],
    ['filtered_fluorocarbon_lanthanum_cerium_slurry', '过滤氟碳镧铈泥浆'],
    ['fluorocarbon_lanthanum_cerium_rare_earth_oxide', '氟碳镧铈稀土氧化物'],
    ['acid_leached_fluorocarbon_lanthanum_cerium_rare_earth_oxide', '酸浸氟碳镧铈稀土氧化物'],
    ['roasted_rare_earth_oxide', '焙烧稀土氧化物'],
    ['wet_rare_earth_oxide', '湿稀土氧化物'],
    ['cerium_rich_rare_earth_oxide', '氧化铈稀土氧化物'],
    ['fluorocarbon_lanthanum_cerium_residual_rare_earth_oxide', '氟碳镧铈罕土氧化物'],
    ['nitrated_fluorocarbon_lanthanum_cerium_residual_rare_earth_oxide', '氮化氟碳镧铈罕土氧化物'],
    ['fluorocarbon_lanthanum_cerium_residual_rare_earth_oxide_suspension', '氟碳镧铈罕土氧化物悬浊液'],
    ['neodymium_rare_earth_concentrate', '钕稀土精'],
    ['diluted_acetone', '稀释丙酮'],
    ['samarium_rare_earth_concentrate', '钐稀土精'],
    ['lanthanum_chloride', '氯化镧'],
    ['neodymium_oxide', '氧化钕'],
    ['samarium_fluoride_concentrate', '氟化钐精'],
    ['calcium_fluoride', '氟化钙'],
    ['samarium_terbium_mixture', '钐-铽混合物'],
    ['hydrated_ammonium_nitrate_slurry', '水合硝酸铵浆液'],
    ['ammonium_nitrate', '硝酸铵'],
    ['nitrated_samarium_terbium_mixture', '氮化钐-铽混合物'],
    ['terbium_nitrate', '硝酸铽'],
    ['rare_earth_i', '稀土(I)'],
    ['rare_earth_ii', '稀土(II)'],
    ['rare_earth_iii', '稀土(III)'],
    ['cadmium_sulfide', '硫镉'],
    ['lanthanite', '镧石'],
    ['cerium_rich_mixture', '富铈混合物'],
    ['yttrium_arsenic_copper_ore', '钇砷铜矿'],
    ['yttrium_thorium_silicate', '硅钍钇矿'],
    ['cryolite', '冰晶石'],
    ['red_lead_ore', '赤铅矿'],
    ['yttrium_niobium_ore', '铌钇矿'],
    ['lepersonite', '莱普生石'],
    ['fluorocarbon_cerium_ore', '氟碳铈矿'],
    ['strontium_oxide', '氧化锶'],
    ['monazite_rare_earth_turbid_slurry', '独居石稀土浊浑液'],
    ['diluted_monazite_rare_earth_mud_slurry', '稀释独居石稀土泥浆'],
    ['zirconium_tetrachloride_solution', '四氯化锆溶液'],
    ['hafnium_tetrachloride_solution', '四氯化铪溶液'],
    ['diluted_sulfuric_monazite_solution', '稀释硫酸独居石溶液'],
    ['ammonium_nitrate_solution', '硝酸铵溶液'],
    ['concentrated_nitrated_monazite_rare_earth_solution', '浓缩氮化独居石稀土溶液'],
    ['nitric_monazite_leaching_mixture', '硝酸独居石浸出混合物'],
    ['concentrated_nitric_monazite_leach_solution', '浓缩硝酸独居石浸出溶液'],
    ['beryllium_copper', '铍铜合金'],
    ['enriched_obsidian', '富集黑曜石'],
    ['atomic_alloy', '原子合金'],
    ["grade_1_purified_water", "I·源初涌动之息(1级净化水)"],
    ['grade_2_purified_water', 'II·微光涤尘之澈(2级净化水)'],
    ['grade_3_purified_water', 'III·晶核汇聚之脉(3级净化水)'],
    ['grade_4_purified_water', 'IV·清流激石之冽(4级净化水)'],
    ['grade_5_purified_water', 'V·深寒凝萃之华(5级净化水)'],
    ['grade_6_purified_water', 'VI·超维滤净之析(6级净化水)'],
    ['grade_7_purified_water', 'VII·星辉盈渊之沁(7级净化水)'],
    ['grade_8_purified_water', 'VIII·太虚归真之寂(8级净化水)']
]
let fluid_js_zh_cn = [
    ['glimmer', '"微光"']
]
let mbd2_key_zh_cn = [
    ['glimmer_collector', '"微光"收集者'],
    ['infused_extracter', '富集提取机']
]
let gt_machine_zh_cn = [
    ['pcb_factory', 'PCB工厂'],
    ['dimensionally_transcendent_isomolecular_reactor', '超维度等分子化工厂'],
    ['directional_void_miner', '定向虚空矿机'],
    ['dissolving_tank', '溶解罐'],
    ['large_gas_collector', '大型集气室'],
    ['large_metallurgic_infuser', '大型冶金灌注机'],
    ['large_rock_breaker', '大型碎岩机'],
    ['dimensionally_transcendent_isothermal_furnace', '超维度等热量冶炼炉'],
    ['dimensionally_transcendent_isovac_freezer', '超维度等真空冷冻机'],
    ['digester', '煮解池'],
    ['large_chemical_plant', '大型化工厂'],
    ['platdur_s_gate', '铂得之门'],
    ['blaze_blast_furnace', '炽炎高炉'],
    ['blaze_blast_smelter', '炽炎熔铸炉'],
    ['cold_ice_freezer', '凛冰冷冻机'],
    ['clarifier_purification_unit', '澄清净化单元'],
    ['petrochemical_factory', '石化工厂']
]
let gt_recipe_type_zh_cn = [
    ['pcb_factory', 'PCB工厂'],
    ['super_chemical_plant', '超级化工厂'],
    ['directional_void_miner', '定向虚空矿机'],
    ['dissolving_tank', '溶解罐'],
    ['large_gas_collector', '大型集气室'],
    ['enrichment_infuser', '富集灌注器'],
    ['glimmer_collector', '"微光"收集器'],
    ['enrichment_chamber', '冶金富集器'],
    ['infused_extracter', '富集提取器'],
    ['plasma_freezer', '等离子冷凝'],
    ['digester', '煮解池'],
    ['platdur_s_gate', '铂得之门'],
    ['clarifier_purification_unit', '澄清净化单元'],
    ['petrochemical_factory', '石化工厂']
]
let machine_single_zh_cn = [
    ['enrichment_infuser', '富集灌注器'],
    ['glimmer_collector', '"微光"收集器'],
    ['enrichment_chamber', '冶金富集器'],
    ['infused_extracter', '富集提取器']
]
ClientEvents.lang('zh_cn', e => {
    key_zh_cn.forEach(([key, value]) => {
        e.add(key, value)
    })
    item_js_key_zh_cn.forEach(([key, value]) => {
        e.add(`item.kubejs.${key}`, value)
    })
    item_ori_key_zh_cn.forEach(([key, value]) => {
        e.add(`item.oritong.${key}`, value)
    })
    block_js_key_zh_cn.forEach(([key, value]) => {
        e.add(`block.kubejs.${key}`, value)
    })
    material_gt_key_zh_cn.forEach(([key, value]) => {
        e.add(`material.gtceu.${key}`, value)
    })
    fluid_js_zh_cn.forEach(([key, name]) => {
        e.add(`item.oritong.${key}_bucket`, `${name}桶`)
        e.add(`fluid.oritong.${key}`, name)
        e.add(`block.oritong.${key}`, name)
    })
    mbd2_key_zh_cn.forEach(([key, name]) => {
        e.add(`block.mbd2.${key}`, name)
    })
    gt_machine_zh_cn.forEach(([key, name]) => {
        e.add(`block.gtceu.${key}`, name)
    })
    gt_recipe_type_zh_cn.forEach(([key, name]) => {
        e.add(`gtceu.${key}`, name)
    })
    machine_single_zh_cn.forEach(([id, name]) => {
        e.add(`block.gtceu.lv_${id}`, `基础${name}`)
        e.add(`block.gtceu.mv_${id}`, `§b进阶${name}`)
        e.add(`block.gtceu.hv_${id}`, `§6进阶${name} I`)
        e.add(`block.gtceu.ev_${id}`, `§d进阶${name} II`)
    })
})
