#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 27 14:29:02 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.3.zip
enableShaders=false
