ServerEvents.recipes(e => {
    e.recipes.gtceu.chemical_reactor().inputFluids(Fluid.of('oritong:latex', 200), Fluid.of('water', 500)).itemInputs('minecraft:clay_ball').outputFluids(Fluid.of('gtceu:rubber', 288)).EUt(4).duration(6 * 20).circuit(3)
    e.recipes.gtceu.chemical_reactor().inputFluids(Fluid.of('oritong:latex', 350), Fluid.of('water', 1000)).itemInputs('3x minecraft:clay_ball', 'gtceu:sulfur_dust').outputFluids(Fluid.of('gtceu:rubber', 1728)).EUt(10).duration(8 * 20)
    e.recipes.gtceu.chemical_reactor().itemInputs('gtceu:calcium_hydroxide_dust').inputFluids(Fluid.of('gtceu:formaldehyde', 8000)).itemOutputs('2x minecraft:sugar', 'tgears:crushed_scorchia').outputFluids(Fluid.of('gtceu:methanol', 1000), Fluid.of('gtceu:formic_acid', 1000)).EUt(120).duration(4 * 20)
    e.recipes.gtceu.chemical_reactor().itemInputs('4x gtceu:tungsten_trioxide_dust').inputFluids(Fluid.of('gtceu:hydrogen', 6000)).itemOutputs('gtceu:tungsten_dust').outputFluids(Fluid.of('water', 3000)).duration(3 * 20).EUt(120)
    e.recipes.gtceu.chemical_reactor().itemInputs('mekanism:dust_diamond', 'gtceu:iridium_dust').inputFluids(Fluid.of('gtceu:methylhydrazine_nitrate_rocket_fuel', 1000), Fluid.of('gtceu:nether_air', 1000)).itemOutputs('2x gtceu:nether_star_dust', '2x gtceu:small_nether_star_dust').EUt(GTValues.VA[GTValues.EV]).duration(8*20).cleanroom(CleanroomType.CLEANROOM)

    e.recipes.gtceu.large_chemical_reactor().inputFluids(Fluid.of('oritong:latex', 350), Fluid.of('water', 1000)).itemInputs('3x minecraft:clay_ball', 'gtceu:sulfur_dust').outputFluids(Fluid.of('gtceu:rubber', 1728)).EUt(10).duration(8 * 20)
    e.recipes.gtceu.large_chemical_reactor().itemInputs('128x minecraft:gunpowder').inputFluids(Fluid.of('gtceu:blaze', 16000), Fluid.of('gtceu:hydrogen_sulfide', 20000), Fluid.of('gtceu:carbon_monoxide', 20000), Fluid.of('gtceu:sulfur_dioxide', 20000), Fluid.of('gtceu:coal_gas', 8000)).outputFluids(Fluid.of('gtceu:nether_air', 1000)).EUt(GTValues.VA[GTValues.EV]).duration(20 * 20)
    e.recipes.gtceu.large_chemical_reactor().itemInputs('64x gtceu:ender_pearl_dust').inputFluids(Fluid.of('gtceu:fuming_nitric_acid', 8000), Fluid.of('gtceu:nitrogen_dioxide', 10000), Fluid.of('gtceu:helium', 10000), Fluid.of('gtceu:radon', 4000), Fluid.of('gtceu:deuterium', 4000)).outputFluids(Fluid.of('gtceu:ender_air', 1000)).EUt(GTValues.VA[GTValues.IV]).duration(20 * 20)
})
