StartupEvents.registry('fluid', e => {
    e.create('oritong:glimmer').thinTexture(0xddffbf).viscosity(100).luminosity(4).tag('oritong:glimmer')
})
GTCEuStartupEvents.registry('gtceu:material', e => {
    e.create('enriched_redstone').liquid().color(0xe60000)
    e.create('diamond_ore_leachate').liquid().color(0xb7fff7)
    e.create('enriched_diamond').liquid().color(0x00f0ff)
    e.create('sodium_hydroxide_solution').liquid().color(0x80f0f0)
    e.create('absolute_ethanol').liquid().color(0xffa500)
    e.create('silica_gel_matrix').liquid().color(0x006060)
    e.create('ethyl_chloroacetate').liquid().color(0xe0f0ff)
    e.create('polyethyl_acetate_mixture').liquid().color(0xffe8a0)
    e.create('diethyl_malonate').liquid().color(0xd0e8ff)
    e.create('ethyl_cyanoacetate').liquid().color(0xf0ffe0)
    e.create('ethyl_cyanoacrylate').liquid().color(0xc8e8ff)
    e.create('pyridine').liquid().color(0xe8e0d0)
    e.create('cobalt_nitrate_solution').liquid().color(0xe04040)
    e.create('light_oil_fraction').liquid().color(0xe8d080)
    e.create('ammonia_solution').liquid().color(0xd8e8f8)
    e.create('crude_light_pyridine').liquid().color(0xb88030)
    e.create('benzene_crude_pyridine').liquid().color(0x906020)
    e.create('azeotropic_crude_pyridine').liquid().color(0xc09840)
    e.create('refined_crude_pyridine').liquid().color(0xd8b850)
    e.create('acetonitrile').liquid().color(0xe8f0e8)
})
