StartupEvents.registry('fluid', e => {
    e.create('oritong:glimmer').thinTexture(0xddffbf).viscosity(100).luminosity(4).tag('oritong:glimmer')
    //e.create("oritong:latex").flowingTexture("kubejs:block/fluid/latex_flow").stillTexture("kubejs:block/fluid/latex_still").bucketColor(0xffffff)
})
GTCEuStartupEvents.registry('gtceu:material', e => {
    e.create('enriched_redstone').liquid().color(0xe60000)
    e.create('diamond_ore_leachate').liquid().color(0xb7fff7)
    e.create('enriched_diamond').liquid().color(0x00f0ff)
    e.create('sodium_hydroxide_solution').liquid().color(0x80f0f0)
    e.create('absolute_ethanol').liquid().color(0xffa500).components("2x carbon", "6x hydrogen", "1x oxygen")
    e.create('silica_gel_matrix').liquid().color(0x006060)
    e.create('ethyl_chloroacetate').liquid().color(0xe0f0ff).components("4x carbon", "7x hydrogen", "1x chlorine", "2x oxygen")
    e.create('polyethyl_acetate_mixture').liquid().color(0xffe8a0)
    e.create('diethyl_malonate').liquid().color(0xd0e8ff).components("7x carbon", "12x hydrogen", "4x oxygen")
    e.create('ethyl_cyanoacetate').liquid().color(0xf0ffe0).components("5x carbon", "7x hydrogen", "1x nitrogen", "2x oxygen")
    e.create('ethyl_cyanoacrylate').liquid().color(0xc8e8ff).components("6x carbon", "7x hydrogen", "1x nitrogen", "2x oxygen")
    e.create('pyridine').liquid().color(0xe8e0d0).components("5x carbon", "5x hydrogen", "1x nitrogen")
    e.create('cobalt_nitrate_solution').liquid().color(0xe04040)
    e.create('light_oil_fraction').liquid().color(0xe8d080)
    e.create('ammonia_solution').liquid().color(0xd8e8f8)
    e.create('crude_light_pyridine').liquid().color(0xb88030)
    e.create('benzene_crude_pyridine').liquid().color(0x906020)
    e.create('azeotropic_crude_pyridine').liquid().color(0xc09840)
    e.create('refined_crude_pyridine').liquid().color(0xd8b850)
    e.create('acetonitrile').liquid().color(0xe8f0e8).components("2x carbon", "3x hydrogen", "1x nitrogen")
    e.create('palladium_nitrate').liquid().color(0xe8a08a).components("1x palladium", "2x nitrogen", "6x oxygen")
    e.create('benzyl_chloride').liquid().color(0x006400).components("7x carbon", "7x hydrogen", "1x chlorine")
    e.create('benzylamine_hydrochloride').liquid().color(0x90ee90).components("7x carbon", "10x hydrogen", "1x chlorine", "1x nitrogen")
    e.create('benzylamine').liquid().color(0xf0e060).components("7x carbon", "9x hydrogen", "1x nitrogen")
    e.create('dried_benzylamine').liquid().color(0xf5ee80)
    e.create('refined_benzylamine').liquid().color(0xfaf0a0)
    e.create('bromobenzene').liquid().color(0x400000).components("6x carbon", "5x hydrogen", "1x bromine")
    e.create('hydrobromic_acid').liquid().color(0xff6060).components("1x hydrogen", "1x bromine")
    e.create('ethylene_oxide').liquid().color(0x00ffff).components("2x carbon", "4x hydrogen", "1x oxygen")
    e.create('wet_ethylene_oxide').liquid().color(0x0080ff)
    e.create('silver_nitrate').liquid().color(0xd0d0ff).components("1x silver", "1x nitrogen", "3x oxygen")
    e.create('fuming_sulfuric_acid').liquid().color(0xf0e080).components("2x hydrogen", "2x sulfur", "7x oxygen")
    e.create('fuming_nitric_acid').liquid().color(0xe0a000).components("1x hydrogen", "1x nitrogen", "3x oxygen")
    e.create('fuming_nitric_acid_mixture').liquid().color(0xd09000)
    e.create('ethylene_glycol').liquid().color(0xc8a070).components("2x carbon", "6x hydrogen", "2x oxygen")
    e.create('gaseous_ethylene_glycol').gas().color(0xc8a070)
    e.create('glyoxal').liquid().color(0xd0c000).components("2x carbon", "2x hydrogen", "2x oxygen")
    e.create('pink_glimmer').liquid().color(0xe47ca9)
    e.create('meteor_slurry').liquid().color(0x1a1a1a)
    e.create('excited_meteor_slurry').liquid().color(0xffaa00)
    e.create('excited_space_fluid').liquid().color(0x004040)
    e.create('space_glimmer_mixture').liquid().color(0x7fff00)
})