const $IngotProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.IngotProperty')
const $DustProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.DustProperty')
const $BlastProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty')
Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.PropertyKey')
Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.ToolProperty')


StartupEvents.registry('item', e => {
    e.create('stone_hammer', 'basic').maxDamage(65).tag('forge:tools/hammers')
    e.create('raw_apothecary')
    e.create('the_source_of_the_earth')
    e.create('originium').rarity('uncommon')
    e.create('originium_shard').rarity('uncommon')
    e.create('orundum').rarity('rare')
    e.create('raw_compressed_fireclay')
    e.create('oritong:steel_upgrade_smithing_template')
    e.create('oritong:diamond_upgrade_smithing_template')
    e.create('oritong:super_glue_package')
    e.create('raw_vacuum_tube')
    e.create('watered_raw_vacuum_tube')
    e.create('wood_ingot').tag('forge:ingots').texture('gtceu:item/empty_wooden_form')
    e.create('general_circuit_ulv').texture('kubejs:item/circuit/general/general_circuit_ulv').tag('gtceu:circuits/ulv').tag('gtceu:circuits')
    e.create('general_circuit_lv').texture('kubejs:item/circuit/general/general_circuit_lv').tag('gtceu:circuits/lv').tag('gtceu:circuits')
    e.create('general_circuit_mv').texture('kubejs:item/circuit/general/general_circuit_mv').tag('gtceu:circuits/mv').tag('gtceu:circuits')
    e.create('general_circuit_hv').texture('kubejs:item/circuit/general/general_circuit_hv').tag('gtceu:circuits/hv').tag('gtceu:circuits')
    e.create('general_circuit_ev').texture('kubejs:item/circuit/general/general_circuit_ev').tag('gtceu:circuits/ev').tag('gtceu:circuits')
    e.create('general_circuit_iv').texture('kubejs:item/circuit/general/general_circuit_iv').tag('gtceu:circuits/iv').tag('gtceu:circuits')
    e.create('general_circuit_luv').texture('kubejs:item/circuit/general/general_circuit_luv').tag('gtceu:circuits/luv').tag('gtceu:circuits')
    e.create('general_circuit_zpm').texture('kubejs:item/circuit/general/general_circuit_zpm').tag('gtceu:circuits/zpm').tag('gtceu:circuits')
    e.create('general_circuit_uv').texture('kubejs:item/circuit/general/general_circuit_uv').tag('gtceu:circuits/uv').tag('gtceu:circuits')
    e.create('general_circuit_uhv').texture('kubejs:item/circuit/general/general_circuit_uhv').tag('gtceu:circuits/uhv').tag('gtceu:circuits')
    e.create('general_circuit_uev').texture('kubejs:item/circuit/general/general_circuit_uev').tag('gtceu:circuits/uev').tag('gtceu:circuits')
    e.create('general_circuit_uiv').texture('kubejs:item/circuit/general/general_circuit_uiv').tag('gtceu:circuits/uiv').tag('gtceu:circuits')
    e.create('general_circuit_uxv').texture('kubejs:item/circuit/general/general_circuit_uxv').tag('gtceu:circuits/uxv').tag('gtceu:circuits')
    e.create('general_circuit_opv').texture('kubejs:item/circuit/general/general_circuit_opv').tag('gtceu:circuits/opv').tag('gtceu:circuits')
    e.create('general_circuit_max').texture('kubejs:item/circuit/general/general_circuit_max').tag('gtceu:circuits/max').tag('gtceu:circuits')
    e.create('silver_catalyst')
    e.create('overworld_data').texture('kubejs:item/data_world')
    e.create('nether_data').texture('kubejs:item/data_nether')
    e.create('end_data').texture('kubejs:item/data_end')
    e.create('lost_item').texture('minecraft:item/barrier')
    e.create('sn1ckers').texture('create:item/bar_of_chocolate').food(foodBuilder => {
        foodBuilder.effect("minecraft:saturation", 75 * 20, 0, 1)
        foodBuilder.effect("farmersdelight:nourishment", 420 * 20, 0, 1)
        foodBuilder.hunger(2)
        foodBuilder.saturation(1)
    })
})

GTCEuStartupEvents.registry('gtceu:material', e => {
    GTMaterials.WroughtIron.addFlags(GTMaterialFlags.GENERATE_ROTOR)
    GTMaterials.Gold.addFlags(GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.Magnalium.addFlags(GTMaterialFlags.GENERATE_FOIL)
    e.create('caminite_brick').ingot().color(0xedd7af).iconSet(GTMaterialIconSet.SHINY).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('infused_alloy').ingot().color(0xea463e).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.LV], 16, 0, true)
    e.create('atomic_alloy').ingot().color(0x6200ad).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('dragon').ingot().color(0x9600ff).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.UXV], 16, 2, false).flags(GTMaterialFlags.GENERATE_PLATE).flags(GTMaterialFlags.GENERATE_GEAR).flags(GTMaterialFlags.GENERATE_ROD)
    e.create('sodium_aluminate').dust().color(0xffffff).components("1x sodium", "1x aluminium", "2x oxygen")
    e.create('aluminum_hydroxide').dust().color(0xa0d0ff).components("1x aluminium", "3x oxygen", "3x hydrogen")
    e.create('alumina').dust().color(0xffffff).components("2x aluminium", "3x oxygen")
    e.create('alumina_ceramic').ingot().color(0xffffff).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('titanium_nitride_ceramic').ingot().color(0xc8a85c).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('wet_sieved_zeolite_powder').dust().color(0x000000)
    e.create('sieved_zeolite_powder').dust().color(0x800080)
    e.create('silica_alumina_gel_powder').dust().color(0x00ffff)
    e.create('silica_gel_powder').dust().color(0xb0e0ff).components("1x silicon", "2x oxygen")
    e.create('chloroacetic_acid').dust().color(0xf0f0f0).components("2x carbon", "3x hydrogen", "1x chlorine", "2x oxygen")
    e.create('cobalt_chloride').dust().color(0x4060ff).components("1x cobalt", "2x chlorine")
    e.create('cobalt_acetate').dust().color(0xe080b0).components("1x cobalt", "4x carbon", "6x hydrogen", "4x oxygen")
    e.create('cobalt_carbonate').dust().color(0xe080a0).components("1x cobalt", "1x carbon", "3x oxygen")
    e.create('monoethyl_malonamide').dust().color(0xf8f8f0)
    e.create('palladium_activated_carbon').dust().color(0x301818)
    e.create('hexamethylenetetramine').dust().color(0xffffff).components("6x carbon", "12x hydrogen", "4x nitrogen")
    e.create('benzyl_hexamethylenetetramine_chloride').dust().color(0xffffff)
    e.create('hexabenzylhexaazaisowurtzitane').dust().color(0xffffff)
    e.create('tetraacetyldibenzylhexaazaisowurtzitane').dust().color(0xffffff)
    e.create('tetraacetylhexaazaisowurtzitane').dust().color(0xffffff)
    e.create('hexanitrohexaazaisowurtzitane').dust().color(0xffffff)
    e.create('mixed_quartz_fiber').dust().color(0xd8e8f0)
    e.create('tungsten_trioxide').dust().color(0x00cc00).components("1x tungsten", "3x oxygen")
    e.create('deactivated_meteor_precipitate').dust().color(0x1a1a1a)
    e.create('beryllium_copper').ingot().color(0x4a8c6f).iconSet(GTMaterialIconSet.METALLIC).flags(GTMaterialFlags.GENERATE_PLATE).blastTemp(2800, 'MID', 1000, 768).components("1x beryllium", "8x copper").flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING).liquid()
})