const $IngotProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.IngotProperty')
const $DustProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.DustProperty')
const $BlastProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty')
Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.PropertyKey')
Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.ToolProperty')


StartupEvents.registry('item', e => {
    e.create('stone_hammer', 'basic').maxDamage(65).tag('forge:tools/hammers')
    e.create('raw_apothecary')
    e.create('the_source_of_the_earth')
    e.create('originium').rarity('uncommon')
    e.create('originium_shard').rarity('uncommon')
    e.create('orundum').rarity('rare')
    e.create('raw_compressed_fireclay')
    e.create('oritong:steel_upgrade_smithing_template')
    e.create('oritong:diamond_upgrade_smithing_template')
    e.create('oritong:super_glue_package')
    e.create('raw_vacuum_tube')
    e.create('watered_raw_vacuum_tube')
    e.create('wood_ingot').tag('forge:ingots').texture('gtceu:item/empty_wooden_form')
    e.create('general_circuit_ulv').texture('kubejs:item/circuit/general/general_circuit_ulv').tag('gtceu:circuits/ulv').tag('gtceu:circuits')
    e.create('general_circuit_lv').texture('kubejs:item/circuit/general/general_circuit_lv').tag('gtceu:circuits/lv').tag('gtceu:circuits')
    e.create('general_circuit_mv').texture('kubejs:item/circuit/general/general_circuit_mv').tag('gtceu:circuits/mv').tag('gtceu:circuits')
    e.create('general_circuit_hv').texture('kubejs:item/circuit/general/general_circuit_hv').tag('gtceu:circuits/hv').tag('gtceu:circuits')
    e.create('general_circuit_ev').texture('kubejs:item/circuit/general/general_circuit_ev').tag('gtceu:circuits/ev').tag('gtceu:circuits')
    e.create('general_circuit_iv').texture('kubejs:item/circuit/general/general_circuit_iv').tag('gtceu:circuits/iv').tag('gtceu:circuits')
    e.create('general_circuit_luv').texture('kubejs:item/circuit/general/general_circuit_luv').tag('gtceu:circuits/luv').tag('gtceu:circuits')
    e.create('general_circuit_zpm').texture('kubejs:item/circuit/general/general_circuit_zpm').tag('gtceu:circuits/zpm').tag('gtceu:circuits')
    e.create('general_circuit_uv').texture('kubejs:item/circuit/general/general_circuit_uv').tag('gtceu:circuits/uv').tag('gtceu:circuits')
    e.create('general_circuit_uhv').texture('kubejs:item/circuit/general/general_circuit_uhv').tag('gtceu:circuits/uhv').tag('gtceu:circuits')
    e.create('general_circuit_uev').texture('kubejs:item/circuit/general/general_circuit_uev').tag('gtceu:circuits/uev').tag('gtceu:circuits')
    e.create('general_circuit_uiv').texture('kubejs:item/circuit/general/general_circuit_uiv').tag('gtceu:circuits/uiv').tag('gtceu:circuits')
    e.create('general_circuit_uxv').texture('kubejs:item/circuit/general/general_circuit_uxv').tag('gtceu:circuits/uxv').tag('gtceu:circuits')
    e.create('general_circuit_opv').texture('kubejs:item/circuit/general/general_circuit_opv').tag('gtceu:circuits/opv').tag('gtceu:circuits')
    e.create('general_circuit_max').texture('kubejs:item/circuit/general/general_circuit_max').tag('gtceu:circuits/max').tag('gtceu:circuits')
    e.create('fear_in_a_bottle')
    e.create('fighting_spirit_in_a_bottle')
    e.create('fog_in_a_bottle')
    e.create('glaceon_in_a_bottle')
    e.create('happiness_in_a_bottle')
    e.create('sand_storm_in_a_bottle')
    e.create('sleppy_in_a_bottle')
    e.create('vaporeon_in_a_bottle')
    e.create('physics_assembler')
    e.create('lost_item').texture('minecraft:item/barrier')
    e.create('sn1ckers').texture('create:item/bar_of_chocolate').food(foodBuilder => {
        foodBuilder.effect("minecraft:saturation", 15 * 20, 0, 1)
        foodBuilder.effect("farmersdelight:nourishment", 180 * 20, 0, 1)
        foodBuilder.hunger(2)
        foodBuilder.saturation(1)
    })
})

GTCEuStartupEvents.registry('gtceu:material', e => {
    GTMaterials.WroughtIron.addFlags(GTMaterialFlags.GENERATE_ROTOR)
    GTMaterials.Gold.addFlags(GTMaterialFlags.GENERATE_GEAR)
    e.create('caminite_brick').ingot().color(0xedd7af).iconSet(GTMaterialIconSet.SHINY).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('infused_alloy').ingot().color(0xea463e).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.LV], 16, 0, true)
    e.create('dragon').ingot().color(0x9600ff).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.UXV], 16, 2, false).flags(GTMaterialFlags.GENERATE_PLATE).flags(GTMaterialFlags.GENERATE_GEAR).flags(GTMaterialFlags.GENERATE_ROD)
    e.create('sodium_aluminate').dust().color(0xffffff)
    e.create('aluminum_hydroxide').dust().color(0xa0d0ff)
    e.create('alumina').dust().color(0xffffff)
    e.create('alumina_ceramic').ingot().color(0xffffff).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('wet_sieved_zeolite_powder').dust().color(0x000000)
    e.create('sieved_zeolite_powder').dust().color(0x800080)
    e.create('silica_alumina_gel_powder').dust().color(0x00ffff)
    e.create('silica_gel_powder').dust().color(0xb0e0ff)
    e.create('chloroacetic_acid').dust().color(0xf0f0f0)
    e.create('cobalt_chloride').dust().color(0x4060ff)
    e.create('cobalt_acetate').dust().color(0xe080b0)
    e.create('cobalt_carbonate').dust().color(0xe080a0)
    e.create('monoethyl_malonamide').dust().color(0xf8f8f0)
})