const $IngotProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.IngotProperty')
const $DustProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.DustProperty')
const $BlastProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty')
const $BlastPropertyBuilder = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty$Builder')
const $MaterialFlag = Java.loadClass("com.gregtechceu.gtceu.api.data.chemical.material.info.MaterialFlag")
const $GasTier = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty$GasTier')
const GENERATE_STARFORGE_HEXLUX = new $MaterialFlag.Builder("generate_starforge_hexlux")
    .requireProps(PropertyKey.INGOT)
    .build()
const GENERATE_RAW_CERAMIC_BLOCK = new $MaterialFlag.Builder("generate_raw_ceramic_block")
    .requireProps(PropertyKey.INGOT)
    .build()

GTCEuStartupEvents.registry('gtceu:tag_prefix', e => {
    e.create('starforge_hexlux')
        .idPattern('%s_starforge_hexlux')
        .defaultTagPath('starforge_hexluxs/%s')
        .unformattedTagPath('starforge_hexluxs')
        .langValue('%s starforge_hexlux')
        .materialAmount(GTValues.M)
        .materialIconType(new GTMaterialIconType('starforge_hexlux'))
        .unificationEnabled(true)
        .generateItem(true)
        .generationCondition(mat => mat.hasFlag(GENERATE_STARFORGE_HEXLUX))
    const rawCeramicBlock = e.create('raw_ceramic_block')
        .idPattern('raw_%s_block')
        .defaultTagPath('storage_blocks/raw_%s')
        .unformattedTagPath('storage_blocks')
        .langValue('Raw %s Block')
        .materialAmount(GTValues.M * 9)
        .materialIconType(new GTMaterialIconType('raw_ceramic_block'))
        .miningToolTag('minecraft:mineable/pickaxe')
        .unificationEnabled(true)
        .generationCondition(mat => mat.hasFlag(GENERATE_RAW_CERAMIC_BLOCK))
    rawCeramicBlock.base.generateBlock(true)
})

StartupEvents.registry('item', e => {
    e.create('stone_hammer', 'basic').maxDamage(65).tag('forge:tools/hammers')
    e.create('raw_apothecary')
    e.create('the_source_of_the_earth')
    e.create('originium').rarity('uncommon')
    e.create('originium_shard').rarity('uncommon')
    e.create('orundum').rarity('rare')
    e.create('raw_compressed_fireclay')
    e.create('oritong:steel_upgrade_smithing_template')
    e.create('oritong:diamond_upgrade_smithing_template')
    e.create('oritong:super_glue_package')
    e.create('raw_vacuum_tube')
    e.create('watered_raw_vacuum_tube')
    e.create('composite_purification_filter')
    e.create('wood_ingot').tag('forge:ingots').texture('gtceu:item/empty_wooden_form')
    e.create('general_circuit_ulv').texture('kubejs:item/circuit/general/general_circuit_ulv').tag('gtceu:circuits/ulv').tag('gtceu:circuits')
    e.create('general_circuit_lv').texture('kubejs:item/circuit/general/general_circuit_lv').tag('gtceu:circuits/lv').tag('gtceu:circuits')
    e.create('general_circuit_mv').texture('kubejs:item/circuit/general/general_circuit_mv').tag('gtceu:circuits/mv').tag('gtceu:circuits')
    e.create('general_circuit_hv').texture('kubejs:item/circuit/general/general_circuit_hv').tag('gtceu:circuits/hv').tag('gtceu:circuits')
    e.create('general_circuit_ev').texture('kubejs:item/circuit/general/general_circuit_ev').tag('gtceu:circuits/ev').tag('gtceu:circuits')
    e.create('general_circuit_iv').texture('kubejs:item/circuit/general/general_circuit_iv').tag('gtceu:circuits/iv').tag('gtceu:circuits')
    e.create('general_circuit_luv').texture('kubejs:item/circuit/general/general_circuit_luv').tag('gtceu:circuits/luv').tag('gtceu:circuits')
    e.create('general_circuit_zpm').texture('kubejs:item/circuit/general/general_circuit_zpm').tag('gtceu:circuits/zpm').tag('gtceu:circuits')
    e.create('general_circuit_uv').texture('kubejs:item/circuit/general/general_circuit_uv').tag('gtceu:circuits/uv').tag('gtceu:circuits')
    e.create('general_circuit_uhv').texture('kubejs:item/circuit/general/general_circuit_uhv').tag('gtceu:circuits/uhv').tag('gtceu:circuits')
    e.create('general_circuit_uev').texture('kubejs:item/circuit/general/general_circuit_uev').tag('gtceu:circuits/uev').tag('gtceu:circuits')
    e.create('general_circuit_uiv').texture('kubejs:item/circuit/general/general_circuit_uiv').tag('gtceu:circuits/uiv').tag('gtceu:circuits')
    e.create('general_circuit_uxv').texture('kubejs:item/circuit/general/general_circuit_uxv').tag('gtceu:circuits/uxv').tag('gtceu:circuits')
    e.create('general_circuit_opv').texture('kubejs:item/circuit/general/general_circuit_opv').tag('gtceu:circuits/opv').tag('gtceu:circuits')
    e.create('general_circuit_max').texture('kubejs:item/circuit/general/general_circuit_max').tag('gtceu:circuits/max').tag('gtceu:circuits')
    e.create('silver_catalyst')
    e.create('overworld_data').texture('kubejs:item/data_world')
    e.create('nether_data').texture('kubejs:item/data_nether')
    e.create('end_data').texture('kubejs:item/data_end')
    e.create('lost_item').texture('minecraft:item/barrier')
    e.create('sn1ckers').texture('create:item/bar_of_chocolate').food(foodBuilder => {
        foodBuilder.effect("minecraft:saturation", 75 * 20, 0, 1)
        foodBuilder.effect("farmersdelight:nourishment", 420 * 20, 0, 1)
        foodBuilder.hunger(2)
        foodBuilder.saturation(1)
    })
    e.create('incomplete_dense_steel_plate', 'create:sequenced_assembly')
})

FunctionalStorageJSEvents.register(e => {
    e.addUpgrade('wood', (ori) => { ori.multiplier(2).fluidMultiplier(1).rangeMultiplier(2).texture("kubejs:item/upgrade/wood").addToTab(true) })
    e.addUpgrade('bronze', (ori) => { ori.multiplier(4).fluidMultiplier(2).rangeMultiplier(4).texture("kubejs:item/upgrade/bronze").addToTab(true) })
    e.addUpgrade('steel', (ori) => { ori.multiplier(8).fluidMultiplier(4).rangeMultiplier(8).texture("kubejs:item/upgrade/steel").addToTab(true) })
    e.addUpgrade('aluminium', (ori) => { ori.multiplier(16).fluidMultiplier(8).rangeMultiplier(16).texture("kubejs:item/upgrade/aluminium").addToTab(true) })
    e.addUpgrade('stainless', (ori) => { ori.multiplier(32).fluidMultiplier(16).rangeMultiplier(32).texture("kubejs:item/upgrade/stainless").addToTab(true) })
    e.addUpgrade('titanium', (ori) => { ori.multiplier(48).fluidMultiplier(24).rangeMultiplier(64).texture("kubejs:item/upgrade/titanium").addToTab(true) })
    e.addUpgrade('tungsten_steel', (ori) => { ori.multiplier(64).fluidMultiplier(32).rangeMultiplier(128).texture("kubejs:item/upgrade/tungsten_steel").addToTab(true) })
})

GTCEuStartupEvents.registry('gtceu:material', e => {
    GTMaterials.WroughtIron.addFlags(GTMaterialFlags.GENERATE_ROTOR)
    GTMaterials.Gold.addFlags(GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.Magnalium.addFlags(GTMaterialFlags.GENERATE_FOIL)
    GTMaterials.Hafnium.addFlags(GTMaterialFlags.GENERATE_PLATE)
    GTMaterials.Zirconium.addFlags(GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.Gadolinium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Zirconium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Zirconium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Zirconium.setProperty(PropertyKey.BLAST, new $BlastProperty(2130, $GasTier.MID, 480, 2130, -1, -1))
    GTMaterials.Hafnium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Hafnium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Holmium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Terbium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Erbium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Dysprosium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Strontium.setProperty(PropertyKey.DUST, new $DustProperty())
    // GTMaterials.Helium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    // GTMaterials.Neon.setProperty(PropertyKey.INGOT, new $IngotProperty())
    // GTMaterials.Argon.setProperty(PropertyKey.INGOT, new $IngotProperty())
    // GTMaterials.Krypton.setProperty(PropertyKey.INGOT, new $IngotProperty())
    // GTMaterials.Xenon.setProperty(PropertyKey.INGOT, new $IngotProperty())
    // GTMaterials.Radon.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Iridium.addFlags(GENERATE_STARFORGE_HEXLUX)
    GTMaterials.Copper.addFlags(GENERATE_STARFORGE_HEXLUX)
    GTMaterials.Iron.addFlags(GENERATE_STARFORGE_HEXLUX)
    GTMaterials.Aluminium.addFlags(GENERATE_STARFORGE_HEXLUX)
    GTMaterials.Titanium.addFlags(GENERATE_STARFORGE_HEXLUX)
    GTMaterials.Obsidian.addFlags(GENERATE_STARFORGE_HEXLUX)
    GTMaterials.Naquadah.addFlags(GENERATE_STARFORGE_HEXLUX)
    e.create('caminite_brick').ingot().color(0xedd7af).iconSet(GTMaterialIconSet.SHINY).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('infused_alloy').ingot().color(0xea463e).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.LV], 16, 0, true)
    e.create('atomic_alloy').ingot().color(0x6200ad).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE)
    e.create('dragon').ingot().color(0x9600ff).iconSet(GTMaterialIconSet.BRIGHT).cableProperties(GTValues.V[GTValues.UXV], 16, 2, false).flags(GTMaterialFlags.GENERATE_PLATE).flags(GTMaterialFlags.GENERATE_GEAR).flags(GTMaterialFlags.GENERATE_ROD)
    e.create('sodium_aluminate').dust().color(0xffffff).components("1x sodium", "1x aluminium", "2x oxygen")
    e.create('aluminum_hydroxide').dust().color(0xa0d0ff).components("1x aluminium", "3x oxygen", "3x hydrogen")
    e.create('alumina').dust().color(0xffffff).components("2x aluminium", "3x oxygen")
    e.create('aluminum_sulfate').dust().color(0xf2f2f2).components("2x aluminium", "3x sulfur", "12x oxygen")
    e.create('alum').gem().color(0xe8f4ff).components("1x potassium", "1x aluminium", "2x sulfur", "24x hydrogen", "20x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('alumina_ceramic').ingot().color(0xffffff).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE).flags(GENERATE_RAW_CERAMIC_BLOCK)
    e.create('titanium_nitride_ceramic').ingot().color(0xc8a85c).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE).flags(GENERATE_RAW_CERAMIC_BLOCK)
    e.create('tungsten_tetraboride_ceramic').ingot().color(0xb2c47a).iconSet(GTMaterialIconSet.BRIGHT).flags(GTMaterialFlags.GENERATE_PLATE).flags(GENERATE_RAW_CERAMIC_BLOCK)
    e.create('tungsten_tetraboride_mixture').dust().color(0x121212).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('wet_sieved_zeolite_powder').dust().color(0x000000)
    e.create('sieved_zeolite_powder').dust().color(0x800080)
    e.create('silica_alumina_gel_powder').dust().color(0x00ffff)
    e.create('silica_gel_powder').dust().color(0xb0e0ff).components("1x silicon", "2x oxygen")
    e.create('chloroacetic_acid').dust().color(0xf0f0f0).components("2x carbon", "3x hydrogen", "1x chlorine", "2x oxygen")
    e.create('cobalt_chloride').dust().color(0x4060ff).components("1x cobalt", "2x chlorine")
    e.create('cobalt_acetate').dust().color(0xe080b0).components("1x cobalt", "4x carbon", "6x hydrogen", "4x oxygen")
    e.create('cobalt_carbonate').dust().color(0xe080a0).components("1x cobalt", "1x carbon", "3x oxygen")
    e.create('monoethyl_malonamide').dust().color(0xf8f8f0)
    e.create('palladium_activated_carbon').dust().color(0x301818)
    e.create('hexamethylenetetramine').dust().color(0xffffff).components("6x carbon", "12x hydrogen", "4x nitrogen")
    e.create('benzyl_hexamethylenetetramine_chloride').dust().color(0xffffff)
    e.create('hexabenzylhexaazaisowurtzitane').dust().color(0xffffff)
    e.create('tetraacetyldibenzylhexaazaisowurtzitane').dust().color(0xffffff)
    e.create('tetraacetylhexaazaisowurtzitane').dust().color(0xffffff)
    e.create('hexanitrohexaazaisowurtzitane').dust().color(0xffffff)
    e.create('mixed_quartz_fiber').dust().color(0xd8e8f0)
    e.create('tungsten_trioxide').dust().color(0x00cc00).components("1x tungsten", "3x oxygen")
    e.create('deactivated_meteor_precipitate').dust().color(0x1a1a1a)
    e.create('thorite').dust().color(0x121a12).components("1x thorium", "1x silicon", "4x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('hafnium_zirconium_oxide_mixture').dust().color(0xe6c59a).components("1x hafnium", "1x zirconium", "4x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('hafnium_oxide').dust().color(0xffffff).components("1x hafnium", "2x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('zirconium_oxide').dust().color(0xffffff).components("1x zirconium", "2x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cerium_dioxide').dust().color(0xffffff).components("1x cerium", "2x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cerium_oxalate').dust().color(0xffffff).components("2x cerium", "6x carbon", "12x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cerium_oxide_iii').dust().color(0xffffff).components("2x cerium", "3x oxygen")
    e.create('europium_oxide_iii').dust().color(0xffffff).components("2x europium", "3x oxygen")
    e.create('europium_oxide').dust().color(0xffffff).components("1x europium", "1x oxygen")
    e.create('zirconium_tetrachloride').dust().color(0x121a12).components("1x zirconium", "4x chlorine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('hafnium_tetrachloride').dust().color(0x121a12).components("1x hafnium", "4x chlorine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('low_purity_hafnium').dust().color(0xf5efda).components("1x hafnium").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('hafnium_iodide').dust().color(0x8c9aa0).components("1x hafnium", "4x iodine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('hafnium_waste').dust().color(0x121212).components("1x hafnium")
    e.create('monazite_rare_earth_residue').dust().color(0x121212).components("1x lanthanum", "1x cerium", "1x neodymium", "1x thorium", "1x phosphorus", "4x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('neutralized_monazite_rare_earth_residue').dust().color(0x121212).components("1x lanthanum", "1x cerium", "1x neodymium", "3x hydrogen", "3x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('concentrated_monazite_hydroxide').dust().color(0x121212).components("1x lanthanum", "1x cerium", "1x neodymium", "3x hydrogen", "3x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cooled_concentrated_nitric_monazite_leach').dust().color(0x121212).components("1x lanthanum", "1x cerium", "1x neodymium", "3x nitrogen", "9x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('red_zircon').dust().color(0x9c4030).components("1x zirconium", "1x silicon", "4x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('monazite_sulfate').dust().color(0xd89820).components("1x lanthanum", "1x cerium", "1x neodymium", "3x sulfur", "12x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('acidic_monazite').dust().color(0xc86d35).components("1x lanthanum", "1x cerium", "1x neodymium", "1x thorium", "1x phosphorus", "2x hydrogen", "1x sulfur", "2x nitrogen", "8x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('thorium_phosphate_filter_cake').dust().color(0xb99d78).components("1x thorium", "1x phosphorus", "4x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('thorium_phosphate_concentrate').dust().color(0xd0bd9f).components("1x thorium", "1x phosphorus", "4x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('uranium_residue').dust().color(0x183c20).components("1x uranium_238", "2x fluorine", "1x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('neutralized_uranium_residue').dust().color(0x3a9a50).components("1x uranium_238", "2x hydrogen", "1x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('dried_concentrated_monazite_rare_earth').dust().color(0xb58a3e).components("1x lanthanum", "1x cerium", "1x neodymium", "3x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cerium_chloride').dust().color(0xb8c8e8).components("1x cerium", "3x chlorine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('monazite_rare_earth_precipitate').dust().color(0x2b1e17).components("1x lanthanum", "1x cerium", "1x neodymium", "1x samarium", "1x europium", "1x gadolinium", "6x carbon", "12x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('heterogeneous_monazite_rare_earth_halide_mixture').dust().color(0x2a3426).components("1x lanthanum", "1x cerium", "1x samarium", "1x europium", "1x gadolinium", "5x chlorine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('saturated_monazite_rare_earth').dust().color(0xb58a3e).components("1x lanthanum", "1x cerium", "1x samarium", "1x gadolinium", "4x chlorine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('samarium_precipitate').dust().color(0x666966).components("2x samarium", "6x carbon", "12x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('sodium_fluorosilicate').dust().color(0xe4e8df).components("2x sodium", "1x silicon", "6x fluorine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('gangue_dust').dust().color(0x000000).components("1x silicon", "1x zirconium", "1x titanium", "1x iron", "6x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('fluorocarbon_lanthanum_cerium_rare_earth_oxide').dust().color(0xc89e56).components("1x lanthanum", "1x cerium", "1x neodymium", "1x samarium", "1x terbium", "1x holmium", "9x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('acid_leached_fluorocarbon_lanthanum_cerium_rare_earth_oxide').dust().color(0xb78242).components("1x lanthanum", "1x cerium", "1x neodymium", "1x samarium", "1x terbium", "1x holmium", "2x hydrogen", "2x chlorine", "9x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('roasted_rare_earth_oxide').dust().color(0xb96532).components("1x lanthanum", "1x cerium", "1x neodymium", "1x samarium", "1x terbium", "1x holmium", "9x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('wet_rare_earth_oxide').dust().color(0xd8c9a6).components("1x lanthanum", "1x cerium", "1x neodymium", "1x samarium", "1x terbium", "1x holmium", "2x hydrogen", "10x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cerium_rich_rare_earth_oxide').dust().color(0xd0ad52).components("1x lanthanum", "2x cerium", "1x neodymium", "1x samarium", "1x terbium", "1x holmium", "9x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('fluorocarbon_lanthanum_cerium_residual_rare_earth_oxide').dust().color(0x9f8c5a).components("1x lanthanum", "1x neodymium", "1x samarium", "1x terbium", "1x holmium", "8x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('neodymium_rare_earth_concentrate').dust().color(0x9e8db5).components("1x lanthanum", "1x neodymium", "3x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('samarium_rare_earth_concentrate').dust().color(0xd1c47a).components("1x samarium", "1x terbium", "1x holmium", "3x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('lanthanum_chloride').dust().color(0xe2e6da).components("1x lanthanum", "3x chlorine")
    e.create('neodymium_oxide').dust().color(0x7878a4).components("2x neodymium", "3x oxygen")
    e.create('samarium_fluoride_concentrate').dust().color(0xe5d994).components("1x samarium", "3x fluorine").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('calcium_fluoride').dust().liquid().color(0xd7e7ec).components("1x calcium", "2x fluorine")
    e.create('samarium_terbium_mixture').dust().color(0x59654c).components("1x samarium", "1x terbium").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('ammonium_nitrate').dust().color(0xe7e1d3).components("2x nitrogen", "4x hydrogen", "3x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('nitrated_samarium_terbium_mixture').dust().color(0x425a49).components("1x samarium", "1x terbium", "2x nitrogen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('terbium_nitrate').dust().color(0xd6a4ad).components("1x terbium", "3x nitrogen", "9x oxygen")
    e.create('rare_earth_i').dust().color(0x9a8d86).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('rare_earth_ii').dust().color(0x7b8d90).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('rare_earth_iii').dust().color(0x8f7b90).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cadmium_sulfide').dust().color(0xe1c84a).components("1x cadmium", "1x sulfur")
    e.create('lanthanite').dust().color(0x9fb59f).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('cerium_rich_mixture').dust().color(0xc8a750).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('yttrium_arsenic_copper_ore').dust().color(0x7e4e46).components("1x cadmium", "1x calcium", "7x copper", "4x arsenic", "21x oxygen", "11x hydrogen")
    e.create('yttrium_thorium_silicate').dust().color(0x8b9a8a).components("2x yttrium", "2x thorium", "2x silicon", "7x oxygen")
    e.create('cryolite').dust().color(0x9ed8e6).components("3x sodium", "1x aluminium", "6x fluorine")
    e.create('red_lead_ore').dust().color(0x9d3e34).components("2x lead", "2x chromium", "3x oxygen", "1x cesium")
    e.create('yttrium_niobium_ore').dust().color(0x3f5365).components("2x yttrium", "10x iron", "2x uranium_235", "3x thorium", "2x niobium", "2x tantalum")
    e.create('lepersonite').dust().color(0x776986).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('fluorocarbon_cerium_ore').dust().color(0xa57a3d).flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('strontium_oxide').dust().color(0xd3c6b5).components("1x strontium", "1x oxygen").flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    e.create('beryllium_copper').ingot().color(0x4a8c6f).iconSet(GTMaterialIconSet.METALLIC).flags(GTMaterialFlags.GENERATE_PLATE).blastTemp(2800, 'MID', 1000, 768).components("1x beryllium", "8x copper").flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING).liquid()
})
